version: '3'

services:
  warehouse:
    build: .
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'nba_warehouse'
      POSTGRES_PASSWORD: 'postgrespw'
