from datetime import datetime

from nba_warehouse.games import Game

json_games = {
    "resource": "scoreboardV2",
    "parameters": {"GameDate": "11/30/2018", "LeagueID": "00", "DayOffset": "0"},
    "resultSets": [
        {
            "name": "GameHeader",
            "headers": [
                "GAME_DATE_EST",
                "GAME_SEQUENCE",
                "GAME_ID",
                "GAME_STATUS_ID",
                "GAME_STATUS_TEXT",
                "GAMECODE",
                "HOME_TEAM_ID",
                "VISITOR_TEAM_ID",
                "SEASON",
                "LIVE_PERIOD",
                "LIVE_PC_TIME",
                "NATL_TV_BROADCASTER_ABBREVIATION",
                "HOME_TV_BROADCASTER_ABBREVIATION",
                "AWAY_TV_BROADCASTER_ABBREVIATION",
                "LIVE_PERIOD_TIME_BCAST",
                "ARENA_NAME",
                "WH_STATUS",
            ],
            "rowSet": [
                [
                    "2018-11-30T00:00:00",
                    1,
                    "0021800319",
                    3,
                    "Final",
                    "20181130/CLEBOS",
                    1610612738,
                    1610612739,
                    "2018",
                    4,
                    "     ",
                    "",
                    "NBCSB",
                    "FSO",
                    "Q4       - ",
                    "TD Garden",
                    1,
                ],
                [
                    "2018-11-30T00:00:00",
                    2,
                    "0021800320",
                    3,
                    "Final",
                    "20181130/UTACHA",
                    1610612766,
                    1610612762,
                    "2018",
                    4,
                    "     ",
                    "",
                    "FSSE-CHA",
                    "ATTSN-RM",
                    "Q4       - ",
                    "Spectrum Center",
                    1,
                ],
            ],
        },
        {
            "name": "LineScore",
            "headers": [
                "GAME_DATE_EST",
                "GAME_SEQUENCE",
                "GAME_ID",
                "TEAM_ID",
                "TEAM_ABBREVIATION",
                "TEAM_CITY_NAME",
                "TEAM_NAME",
                "TEAM_WINS_LOSSES",
                "PTS_QTR1",
                "PTS_QTR2",
                "PTS_QTR3",
                "PTS_QTR4",
                "PTS_OT1",
                "PTS_OT2",
                "PTS_OT3",
                "PTS_OT4",
                "PTS_OT5",
                "PTS_OT6",
                "PTS_OT7",
                "PTS_OT8",
                "PTS_OT9",
                "PTS_OT10",
                "PTS",
                "FG_PCT",
                "FT_PCT",
                "FG3_PCT",
                "AST",
                "REB",
                "TOV",
            ],
            "rowSet": [
                [
                    "2018-11-30T00:00:00",
                    1,
                    "0021800319",
                    1610612739,
                    "CLE",
                    "Cleveland",
                    "Cavaliers",
                    "4-17",
                    26,
                    26,
                    20,
                    23,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    95,
                    0.39,
                    0.8,
                    0.318,
                    18,
                    36,
                    13,
                ],
                [
                    "2018-11-30T00:00:00",
                    1,
                    "0021800319",
                    1610612738,
                    "BOS",
                    "Boston",
                    "Celtics",
                    "12-10",
                    30,
                    32,
                    39,
                    27,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    128,
                    0.533,
                    0.813,
                    0.548,
                    30,
                    47,
                    10,
                ],
                [
                    "2018-11-30T00:00:00",
                    2,
                    "0021800320",
                    1610612762,
                    "UTA",
                    "Utah",
                    "Jazz",
                    "11-12",
                    33,
                    24,
                    34,
                    28,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    119,
                    0.543,
                    0.722,
                    0.45,
                    32,
                    41,
                    14,
                ],
                [
                    "2018-11-30T00:00:00",
                    2,
                    "0021800320",
                    1610612766,
                    "CHA",
                    "Charlotte",
                    "Hornets",
                    "11-11",
                    19,
                    34,
                    30,
                    28,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    111,
                    0.495,
                    0.615,
                    0.321,
                    19,
                    38,
                    8,
                ],
            ],
        },
        {
            "name": "SeriesStandings",
            "headers": [
                "GAME_ID",
                "HOME_TEAM_ID",
                "VISITOR_TEAM_ID",
                "GAME_DATE_EST",
                "HOME_TEAM_WINS",
                "HOME_TEAM_LOSSES",
                "SERIES_LEADER",
            ],
            "rowSet": [
                [
                    "0021800319",
                    1610612738,
                    1610612739,
                    "2018-11-30T00:00:00",
                    3,
                    0,
                    "Boston",
                ],
                [
                    "0021800320",
                    1610612766,
                    1610612762,
                    "2018-11-30T00:00:00",
                    0,
                    1,
                    "Utah",
                ],
            ],
        },
        {
            "name": "LastMeeting",
            "headers": [
                "GAME_ID",
                "LAST_GAME_ID",
                "LAST_GAME_DATE_EST",
                "LAST_GAME_HOME_TEAM_ID",
                "LAST_GAME_HOME_TEAM_CITY",
                "LAST_GAME_HOME_TEAM_NAME",
                "LAST_GAME_HOME_TEAM_ABBREVIATION",
                "LAST_GAME_HOME_TEAM_POINTS",
                "LAST_GAME_VISITOR_TEAM_ID",
                "LAST_GAME_VISITOR_TEAM_CITY",
                "LAST_GAME_VISITOR_TEAM_NAME",
                "LAST_GAME_VISITOR_TEAM_CITY1",
                "LAST_GAME_VISITOR_TEAM_POINTS",
            ],
            "rowSet": [
                [
                    "0021800319",
                    "0011800040",
                    "2018-10-06T00:00:00",
                    1610612738,
                    "Boston",
                    "Celtics",
                    "BOS",
                    102,
                    1610612739,
                    "Cleveland",
                    "Cavaliers",
                    "CLE",
                    113,
                ],
                [
                    "0021800320",
                    "0021700824",
                    "2018-02-09T00:00:00",
                    1610612766,
                    "Charlotte",
                    "Hornets",
                    "CHA",
                    94,
                    1610612762,
                    "Utah",
                    "Jazz",
                    "UTA",
                    106,
                ],
            ],
        },
        {
            "name": "EastConfStandingsByDay",
            "headers": [
                "TEAM_ID",
                "LEAGUE_ID",
                "SEASON_ID",
                "STANDINGSDATE",
                "CONFERENCE",
                "TEAM",
                "G",
                "W",
                "L",
                "W_PCT",
                "HOME_RECORD",
                "ROAD_RECORD",
            ],
            "rowSet": [
                [
                    1610612761,
                    "00",
                    "22018",
                    "11/30/2018",
                    "East",
                    "Toronto",
                    23,
                    19,
                    4,
                    0.826,
                    "10-2",
                    "9-2",
                ],
                [
                    1610612749,
                    "00",
                    "22018",
                    "11/30/2018",
                    "East",
                    "Milwaukee",
                    21,
                    15,
                    6,
                    0.714,
                    "11-2",
                    "4-4",
                ],
            ],
        },
        {
            "name": "WestConfStandingsByDay",
            "headers": [
                "TEAM_ID",
                "LEAGUE_ID",
                "SEASON_ID",
                "STANDINGSDATE",
                "CONFERENCE",
                "TEAM",
                "G",
                "W",
                "L",
                "W_PCT",
                "HOME_RECORD",
                "ROAD_RECORD",
            ],
            "rowSet": [
                [
                    1610612746,
                    "00",
                    "22018",
                    "11/30/2018",
                    "West",
                    "LA Clippers",
                    21,
                    15,
                    6,
                    0.714,
                    "9-1",
                    "6-5",
                ],
                [
                    1610612743,
                    "00",
                    "22018",
                    "11/30/2018",
                    "West",
                    "Denver",
                    22,
                    15,
                    7,
                    0.682,
                    "9-3",
                    "6-4",
                ],
            ],
        },
        {
            "name": "Available",
            "headers": ["GAME_ID", "PT_AVAILABLE"],
            "rowSet": [["0021800328", 1], ["0021800326", 1]],
        },
        {
            "name": "TeamLeaders",
            "headers": [
                "GAME_ID",
                "TEAM_ID",
                "TEAM_CITY",
                "TEAM_NICKNAME",
                "TEAM_ABBREVIATION",
                "PTS_PLAYER_ID",
                "PTS_PLAYER_NAME",
                "PTS",
                "REB_PLAYER_ID",
                "REB_PLAYER_NAME",
                "REB",
                "AST_PLAYER_ID",
                "AST_PLAYER_NAME",
                "AST",
            ],
            "rowSet": [
                [
                    "0021800319",
                    1610612738,
                    "Boston",
                    "Celtics",
                    "BOS",
                    202681,
                    "Kyrie Irving",
                    29,
                    203382,
                    "Aron Baynes",
                    9,
                    203935,
                    "Marcus Smart",
                    7,
                ],
                [
                    "0021800319",
                    1610612739,
                    "Cleveland",
                    "Cavaliers",
                    "CLE",
                    203903,
                    "Jordan Clarkson",
                    16,
                    202684,
                    "Tristan Thompson",
                    12,
                    202684,
                    "Tristan Thompson",
                    4,
                ],
            ],
        },
        {
            "name": "TicketLinks",
            "headers": ["GAME_ID", "LEAG_TIX"],
            "rowSet": [
                [
                    "0021800319",
                    "https://ticketmaster.com/event/0100550ADB09D7C3?brand=nba&extcmp=gw513142&wt.mc_id=NBA_LEAGUE_BOS_SINGLE_GAME_LINK&utm_source=NBA.com&utm_medium=client&utm_campaign=NBA_LEAGUE_BOS&utm_content=SINGLE_GAME_LINK",
                ],
                [
                    "0021800329",
                    "https://www.ticketmaster.com/portland-trail-blazers-vs-denver-nuggets-portland-oregon-11-30-2018/event/0F005515A8904734?brand=nba&extcmp=gw513160&wt.mc_id=NBA_LEAGUE_POR_SINGLE_GAME_LINK&utm_source=NBA.com&utm_medium=client&utm_campaign=NBA_LEAGUE_POR&utm",
                ],
            ],
        },
        {"name": "WinProbability", "headers": [], "rowSet": []},
    ],
}

games = [
    Game("0021800319", datetime(2018, 11, 30), 2018, 1610612738, 1610612739, 128, 95),
    Game("0021800320", datetime(2018, 11, 30), 2018, 1610612766, 1610612762, 111, 119),
]

json_teams = {
    "_internal": {
        "pubDateTime": "2018-08-30 20:00:04.422",
        "xslt": "xsl/league/roster/marty_teams_list.xsl",
        "eventName": "league_roster",
    },
    "league": {
        "standard": [
            {
                "isNBAFranchise": "false",
                "isAllStar": "true",
                "city": "USA",
                "altCityName": "USA",
                "fullName": "USA",
                "tricode": "USA",
                "teamId": "1610616843",
                "nickname": "USA",
                "urlName": "usa",
                "confName": "East",
                "divName": "East",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "true",
                "city": "World",
                "altCityName": "World",
                "fullName": "World",
                "tricode": "WLD",
                "teamId": "1610616844",
                "nickname": "World",
                "urlName": "world",
                "confName": "East",
                "divName": "East",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "true",
                "city": "Team",
                "altCityName": "Team",
                "fullName": "All-Stars",
                "tricode": "EST",
                "teamId": "1699999999",
                "nickname": "All-Stars",
                "urlName": "assn_away",
                "confName": "East",
                "divName": "East",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "true",
                "city": "Team",
                "altCityName": "Team",
                "fullName": "All-Stars",
                "tricode": "WST",
                "teamId": "1699999998",
                "nickname": "All-Stars",
                "urlName": "assn_home",
                "confName": "West",
                "divName": "West",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "true",
                "city": "Team Giannis",
                "altCityName": "Team Giannis",
                "fullName": "Team Giannis",
                "tricode": "GNS",
                "teamId": "1610616833",
                "nickname": "Team Giannis",
                "urlName": "team_giannis",
                "confName": "East",
                "divName": "East",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "true",
                "city": "Team LeBron",
                "altCityName": "Team LeBron",
                "fullName": "Team LeBron",
                "tricode": "LBN",
                "teamId": "1610616834",
                "nickname": "Team LeBron",
                "urlName": "team_lebron",
                "confName": "West",
                "divName": "West",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Team",
                "altCityName": "Team",
                "fullName": "Team Africa",
                "tricode": "AFR",
                "teamId": "12326",
                "nickname": "Africa",
                "urlName": "africa",
                "confName": "",
                "divName": "",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Team",
                "altCityName": "Team",
                "fullName": "Team World",
                "tricode": "WLD",
                "teamId": "12327",
                "nickname": "World",
                "urlName": "world",
                "confName": "",
                "divName": "",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Adelaide",
                "altCityName": "Adelaide",
                "fullName": "Adelaide 36ers",
                "tricode": "ADL",
                "teamId": "15019",
                "nickname": "36ers",
                "urlName": "36ers",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Atlanta",
                "altCityName": "Atlanta",
                "fullName": "Atlanta Hawks",
                "tricode": "ATL",
                "teamId": "1610612737",
                "nickname": "Hawks",
                "urlName": "hawks",
                "confName": "East",
                "divName": "Southeast",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Beijing",
                "altCityName": "Beijing",
                "fullName": "Beijing Ducks",
                "tricode": "BJD",
                "teamId": "15021",
                "nickname": "Ducks",
                "urlName": "ducks",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Boston",
                "altCityName": "Boston",
                "fullName": "Boston Celtics",
                "tricode": "BOS",
                "teamId": "1610612738",
                "nickname": "Celtics",
                "urlName": "celtics",
                "confName": "East",
                "divName": "Atlantic",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Brooklyn",
                "altCityName": "Brooklyn",
                "fullName": "Brooklyn Nets",
                "tricode": "BKN",
                "teamId": "1610612751",
                "nickname": "Nets",
                "urlName": "nets",
                "confName": "East",
                "divName": "Atlantic",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Charlotte",
                "altCityName": "Charlotte",
                "fullName": "Charlotte Hornets",
                "tricode": "CHA",
                "teamId": "1610612766",
                "nickname": "Hornets",
                "urlName": "hornets",
                "confName": "East",
                "divName": "Southeast",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Chicago",
                "altCityName": "Chicago",
                "fullName": "Chicago Bulls",
                "tricode": "CHI",
                "teamId": "1610612741",
                "nickname": "Bulls",
                "urlName": "bulls",
                "confName": "East",
                "divName": "Central",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Cleveland",
                "altCityName": "Cleveland",
                "fullName": "Cleveland Cavaliers",
                "tricode": "CLE",
                "teamId": "1610612739",
                "nickname": "Cavaliers",
                "urlName": "cavaliers",
                "confName": "East",
                "divName": "Central",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Dallas",
                "altCityName": "Dallas",
                "fullName": "Dallas Mavericks",
                "tricode": "DAL",
                "teamId": "1610612742",
                "nickname": "Mavericks",
                "urlName": "mavericks",
                "confName": "West",
                "divName": "Southwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Denver",
                "altCityName": "Denver",
                "fullName": "Denver Nuggets",
                "tricode": "DEN",
                "teamId": "1610612743",
                "nickname": "Nuggets",
                "urlName": "nuggets",
                "confName": "West",
                "divName": "Northwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Detroit",
                "altCityName": "Detroit",
                "fullName": "Detroit Pistons",
                "tricode": "DET",
                "teamId": "1610612765",
                "nickname": "Pistons",
                "urlName": "pistons",
                "confName": "East",
                "divName": "Central",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Golden State",
                "altCityName": "Golden State",
                "fullName": "Golden State Warriors",
                "tricode": "GSW",
                "teamId": "1610612744",
                "nickname": "Warriors",
                "urlName": "warriors",
                "confName": "West",
                "divName": "Pacific",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Guangzhou",
                "altCityName": "Guangzhou",
                "fullName": "Guangzhou Long-Lions",
                "tricode": "GUA",
                "teamId": "15018",
                "nickname": "Long-Lions",
                "urlName": "long-lions",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Haifa",
                "altCityName": "Haifa",
                "fullName": "Maccabi Haifa",
                "tricode": "MAC",
                "teamId": "93",
                "nickname": "Maccabi Haifa",
                "urlName": "maccabi_haifa",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Houston",
                "altCityName": "Houston",
                "fullName": "Houston Rockets",
                "tricode": "HOU",
                "teamId": "1610612745",
                "nickname": "Rockets",
                "urlName": "rockets",
                "confName": "West",
                "divName": "Southwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Indiana",
                "altCityName": "Indiana",
                "fullName": "Indiana Pacers",
                "tricode": "IND",
                "teamId": "1610612754",
                "nickname": "Pacers",
                "urlName": "pacers",
                "confName": "East",
                "divName": "Central",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "LA",
                "altCityName": "LA Clippers",
                "fullName": "LA Clippers",
                "tricode": "LAC",
                "teamId": "1610612746",
                "nickname": "Clippers",
                "urlName": "clippers",
                "confName": "West",
                "divName": "Pacific",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Los Angeles",
                "altCityName": "Los Angeles Lakers",
                "fullName": "Los Angeles Lakers",
                "tricode": "LAL",
                "teamId": "1610612747",
                "nickname": "Lakers",
                "urlName": "lakers",
                "confName": "West",
                "divName": "Pacific",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Melbourne",
                "altCityName": "Melbourne",
                "fullName": "Melbourne United",
                "tricode": "MEL",
                "teamId": "15016",
                "nickname": "United",
                "urlName": "united",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Memphis",
                "altCityName": "Memphis",
                "fullName": "Memphis Grizzlies",
                "tricode": "MEM",
                "teamId": "1610612763",
                "nickname": "Grizzlies",
                "urlName": "grizzlies",
                "confName": "West",
                "divName": "Southwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Miami",
                "altCityName": "Miami",
                "fullName": "Miami Heat",
                "tricode": "MIA",
                "teamId": "1610612748",
                "nickname": "Heat",
                "urlName": "heat",
                "confName": "East",
                "divName": "Southeast",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Milwaukee",
                "altCityName": "Milwaukee",
                "fullName": "Milwaukee Bucks",
                "tricode": "MIL",
                "teamId": "1610612749",
                "nickname": "Bucks",
                "urlName": "bucks",
                "confName": "East",
                "divName": "Central",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Minnesota",
                "altCityName": "Minnesota",
                "fullName": "Minnesota Timberwolves",
                "tricode": "MIN",
                "teamId": "1610612750",
                "nickname": "Timberwolves",
                "urlName": "timberwolves",
                "confName": "West",
                "divName": "Northwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "New Orleans",
                "altCityName": "New Orleans",
                "fullName": "New Orleans Pelicans",
                "tricode": "NOP",
                "teamId": "1610612740",
                "nickname": "Pelicans",
                "urlName": "pelicans",
                "confName": "West",
                "divName": "Southwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "New York",
                "altCityName": "New York",
                "fullName": "New York Knicks",
                "tricode": "NYK",
                "teamId": "1610612752",
                "nickname": "Knicks",
                "urlName": "knicks",
                "confName": "East",
                "divName": "Atlantic",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "New Zealand",
                "altCityName": "New Zealand",
                "fullName": "New Zealand Breakers",
                "tricode": "NZB",
                "teamId": "15020",
                "nickname": "Breakers",
                "urlName": "breakers",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Oklahoma City",
                "altCityName": "Oklahoma City",
                "fullName": "Oklahoma City Thunder",
                "tricode": "OKC",
                "teamId": "1610612760",
                "nickname": "Thunder",
                "urlName": "thunder",
                "confName": "West",
                "divName": "Northwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Orlando",
                "altCityName": "Orlando",
                "fullName": "Orlando Magic",
                "tricode": "ORL",
                "teamId": "1610612753",
                "nickname": "Magic",
                "urlName": "magic",
                "confName": "East",
                "divName": "Southeast",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Perth",
                "altCityName": "Perth",
                "fullName": "Perth Wildcats",
                "tricode": "PER",
                "teamId": "104",
                "nickname": "Wildcats",
                "urlName": "wildcats",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Philadelphia",
                "altCityName": "Philadelphia",
                "fullName": "Philadelphia 76ers",
                "tricode": "PHI",
                "teamId": "1610612755",
                "nickname": "76ers",
                "urlName": "sixers",
                "confName": "East",
                "divName": "Atlantic",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Phoenix",
                "altCityName": "Phoenix",
                "fullName": "Phoenix Suns",
                "tricode": "PHX",
                "teamId": "1610612756",
                "nickname": "Suns",
                "urlName": "suns",
                "confName": "West",
                "divName": "Pacific",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Portland",
                "altCityName": "Portland",
                "fullName": "Portland Trail Blazers",
                "tricode": "POR",
                "teamId": "1610612757",
                "nickname": "Trail Blazers",
                "urlName": "blazers",
                "confName": "West",
                "divName": "Northwest",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Rio de Janeiro",
                "altCityName": "Rio de Janeiro",
                "fullName": "Rio de Janeiro Flamengo",
                "tricode": "FLA",
                "teamId": "12325",
                "nickname": "Flamengo",
                "urlName": "flamengo",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Sacramento",
                "altCityName": "Sacramento",
                "fullName": "Sacramento Kings",
                "tricode": "SAC",
                "teamId": "1610612758",
                "nickname": "Kings",
                "urlName": "kings",
                "confName": "West",
                "divName": "Pacific",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "San Antonio",
                "altCityName": "San Antonio",
                "fullName": "San Antonio Spurs",
                "tricode": "SAS",
                "teamId": "1610612759",
                "nickname": "Spurs",
                "urlName": "spurs",
                "confName": "West",
                "divName": "Southwest",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Shanghai",
                "altCityName": "Shanghai",
                "fullName": "Shanghai Sharks",
                "tricode": "SDS",
                "teamId": "12329",
                "nickname": "Shanghai Sharks",
                "urlName": "shanghai_sharks",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Sydney",
                "altCityName": "Sydney",
                "fullName": "Sydney Kings",
                "tricode": "SYD",
                "teamId": "15015",
                "nickname": "Kings",
                "urlName": "kings",
                "confName": "Intl",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Toronto",
                "altCityName": "Toronto",
                "fullName": "Toronto Raptors",
                "tricode": "TOR",
                "teamId": "1610612761",
                "nickname": "Raptors",
                "urlName": "raptors",
                "confName": "East",
                "divName": "Atlantic",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Utah",
                "altCityName": "Utah",
                "fullName": "Utah Jazz",
                "tricode": "UTA",
                "teamId": "1610612762",
                "nickname": "Jazz",
                "urlName": "jazz",
                "confName": "West",
                "divName": "Northwest",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Washington",
                "altCityName": "Washington",
                "fullName": "Washington Wizards",
                "tricode": "WAS",
                "teamId": "1610612764",
                "nickname": "Wizards",
                "urlName": "wizards",
                "confName": "East",
                "divName": "Southeast",
            },
        ],
        "africa": [
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Team",
                "altCityName": "Team",
                "fullName": "Team Africa",
                "tricode": "AFR",
                "teamId": "12326",
                "nickname": "Africa",
                "urlName": "africa",
                "confName": "",
                "divName": "",
            },
            {
                "isNBAFranchise": "false",
                "isAllStar": "false",
                "city": "Team",
                "altCityName": "Team",
                "fullName": "Team World",
                "tricode": "WLD",
                "teamId": "12327",
                "nickname": "World",
                "urlName": "world",
                "confName": "",
                "divName": "",
            },
        ],
        "sacramento": [
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Golden State",
                "altCityName": "Golden State",
                "fullName": "Golden State Warriors",
                "tricode": "GSW",
                "teamId": "1610612744",
                "nickname": "Warriors",
                "urlName": "warriors",
                "confName": "Sacramento",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Los Angeles",
                "altCityName": "Los Angeles Lakers",
                "fullName": "Los Angeles Lakers",
                "tricode": "LAL",
                "teamId": "1610612747",
                "nickname": "Lakers",
                "urlName": "lakers",
                "confName": "Sacramento",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Miami",
                "altCityName": "Miami",
                "fullName": "Miami Heat",
                "tricode": "MIA",
                "teamId": "1610612748",
                "nickname": "Heat",
                "urlName": "heat",
                "confName": "Sacramento",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Sacramento",
                "altCityName": "Sacramento",
                "fullName": "Sacramento Kings",
                "tricode": "SAC",
                "teamId": "1610612758",
                "nickname": "Kings",
                "urlName": "kings",
                "confName": "Sacramento",
                "divName": "",
            },
        ],
        "vegas": [
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Atlanta",
                "altCityName": "Atlanta",
                "fullName": "Atlanta Hawks",
                "tricode": "ATL",
                "teamId": "1610612737",
                "nickname": "Hawks",
                "urlName": "hawks",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Boston",
                "altCityName": "Boston",
                "fullName": "Boston Celtics",
                "tricode": "BOS",
                "teamId": "1610612738",
                "nickname": "Celtics",
                "urlName": "celtics",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Brooklyn",
                "altCityName": "Brooklyn",
                "fullName": "Brooklyn Nets",
                "tricode": "BKN",
                "teamId": "1610612751",
                "nickname": "Nets",
                "urlName": "nets",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Charlotte",
                "altCityName": "Charlotte",
                "fullName": "Charlotte Hornets",
                "tricode": "CHA",
                "teamId": "1610612766",
                "nickname": "Hornets",
                "urlName": "hornets",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Chicago",
                "altCityName": "Chicago",
                "fullName": "Chicago Bulls",
                "tricode": "CHI",
                "teamId": "1610612741",
                "nickname": "Bulls",
                "urlName": "bulls",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Cleveland",
                "altCityName": "Cleveland",
                "fullName": "Cleveland Cavaliers",
                "tricode": "CLE",
                "teamId": "1610612739",
                "nickname": "Cavaliers",
                "urlName": "cavaliers",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Dallas",
                "altCityName": "Dallas",
                "fullName": "Dallas Mavericks",
                "tricode": "DAL",
                "teamId": "1610612742",
                "nickname": "Mavericks",
                "urlName": "mavericks",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Denver",
                "altCityName": "Denver",
                "fullName": "Denver Nuggets",
                "tricode": "DEN",
                "teamId": "1610612743",
                "nickname": "Nuggets",
                "urlName": "nuggets",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Detroit",
                "altCityName": "Detroit",
                "fullName": "Detroit Pistons",
                "tricode": "DET",
                "teamId": "1610612765",
                "nickname": "Pistons",
                "urlName": "pistons",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Golden State",
                "altCityName": "Golden State",
                "fullName": "Golden State Warriors",
                "tricode": "GSW",
                "teamId": "1610612744",
                "nickname": "Warriors",
                "urlName": "warriors",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Houston",
                "altCityName": "Houston",
                "fullName": "Houston Rockets",
                "tricode": "HOU",
                "teamId": "1610612745",
                "nickname": "Rockets",
                "urlName": "rockets",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Indiana",
                "altCityName": "Indiana",
                "fullName": "Indiana Pacers",
                "tricode": "IND",
                "teamId": "1610612754",
                "nickname": "Pacers",
                "urlName": "pacers",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "LA",
                "altCityName": "LA Clippers",
                "fullName": "LA Clippers",
                "tricode": "LAC",
                "teamId": "1610612746",
                "nickname": "Clippers",
                "urlName": "clippers",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Los Angeles",
                "altCityName": "Los Angeles Lakers",
                "fullName": "Los Angeles Lakers",
                "tricode": "LAL",
                "teamId": "1610612747",
                "nickname": "Lakers",
                "urlName": "lakers",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Memphis",
                "altCityName": "Memphis",
                "fullName": "Memphis Grizzlies",
                "tricode": "MEM",
                "teamId": "1610612763",
                "nickname": "Grizzlies",
                "urlName": "grizzlies",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Miami",
                "altCityName": "Miami",
                "fullName": "Miami Heat",
                "tricode": "MIA",
                "teamId": "1610612748",
                "nickname": "Heat",
                "urlName": "heat",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Milwaukee",
                "altCityName": "Milwaukee",
                "fullName": "Milwaukee Bucks",
                "tricode": "MIL",
                "teamId": "1610612749",
                "nickname": "Bucks",
                "urlName": "bucks",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Minnesota",
                "altCityName": "Minnesota",
                "fullName": "Minnesota Timberwolves",
                "tricode": "MIN",
                "teamId": "1610612750",
                "nickname": "Timberwolves",
                "urlName": "timberwolves",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "New Orleans",
                "altCityName": "New Orleans",
                "fullName": "New Orleans Pelicans",
                "tricode": "NOP",
                "teamId": "1610612740",
                "nickname": "Pelicans",
                "urlName": "pelicans",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "New York",
                "altCityName": "New York",
                "fullName": "New York Knicks",
                "tricode": "NYK",
                "teamId": "1610612752",
                "nickname": "Knicks",
                "urlName": "knicks",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Oklahoma City",
                "altCityName": "Oklahoma City",
                "fullName": "Oklahoma City Thunder",
                "tricode": "OKC",
                "teamId": "1610612760",
                "nickname": "Thunder",
                "urlName": "thunder",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Orlando",
                "altCityName": "Orlando",
                "fullName": "Orlando Magic",
                "tricode": "ORL",
                "teamId": "1610612753",
                "nickname": "Magic",
                "urlName": "magic",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Philadelphia",
                "altCityName": "Philadelphia",
                "fullName": "Philadelphia 76ers",
                "tricode": "PHI",
                "teamId": "1610612755",
                "nickname": "76ers",
                "urlName": "sixers",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Phoenix",
                "altCityName": "Phoenix",
                "fullName": "Phoenix Suns",
                "tricode": "PHX",
                "teamId": "1610612756",
                "nickname": "Suns",
                "urlName": "suns",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Portland",
                "altCityName": "Portland",
                "fullName": "Portland Trail Blazers",
                "tricode": "POR",
                "teamId": "1610612757",
                "nickname": "Trail Blazers",
                "urlName": "blazers",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Sacramento",
                "altCityName": "Sacramento",
                "fullName": "Sacramento Kings",
                "tricode": "SAC",
                "teamId": "1610612758",
                "nickname": "Kings",
                "urlName": "kings",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "San Antonio",
                "altCityName": "San Antonio",
                "fullName": "San Antonio Spurs",
                "tricode": "SAS",
                "teamId": "1610612759",
                "nickname": "Spurs",
                "urlName": "spurs",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Toronto",
                "altCityName": "Toronto",
                "fullName": "Toronto Raptors",
                "tricode": "TOR",
                "teamId": "1610612761",
                "nickname": "Raptors",
                "urlName": "raptors",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Utah",
                "altCityName": "Utah",
                "fullName": "Utah Jazz",
                "tricode": "UTA",
                "teamId": "1610612762",
                "nickname": "Jazz",
                "urlName": "jazz",
                "confName": "summer",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Washington",
                "altCityName": "Washington",
                "fullName": "Washington Wizards",
                "tricode": "WAS",
                "teamId": "1610612764",
                "nickname": "Wizards",
                "urlName": "wizards",
                "confName": "summer",
                "divName": "",
            },
        ],
        "utah": [
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Atlanta",
                "altCityName": "Atlanta",
                "fullName": "Atlanta Hawks",
                "tricode": "ATL",
                "teamId": "1610612737",
                "nickname": "Hawks",
                "urlName": "hawks",
                "confName": "Utah",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Memphis",
                "altCityName": "Memphis",
                "fullName": "Memphis Grizzlies",
                "tricode": "MEM",
                "teamId": "1610612763",
                "nickname": "Grizzlies",
                "urlName": "grizzlies",
                "confName": "Utah",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "San Antonio",
                "altCityName": "San Antonio",
                "fullName": "San Antonio Spurs",
                "tricode": "SAS",
                "teamId": "1610612759",
                "nickname": "Spurs",
                "urlName": "spurs",
                "confName": "Utah",
                "divName": "",
            },
            {
                "isNBAFranchise": "true",
                "isAllStar": "false",
                "city": "Utah",
                "altCityName": "Utah",
                "fullName": "Utah Jazz",
                "tricode": "UTA",
                "teamId": "1610612762",
                "nickname": "Jazz",
                "urlName": "jazz",
                "confName": "Utah",
                "divName": "",
            },
        ],
    },
}
